/*
 * Copyright (c) 2005 Perception Software. All Rights Reserved.
 */
package jgsl.io;

/**
 * A general script message generated by the parser.
 *
 * @author zenarchitect
 * @version $Id: ScriptMessage.java,v 1.2 2005/05/16 00:54:16 zenarchitect Exp $
 */
public class ScriptMessage implements Message {
    private String message;

    public ScriptMessage(String message) {
        this.message = message;
    }

    /**
     * Returns the type of message
     *
     * @return MessageType
     */
    public MessageType getType() {
        return Message.MessageType.MESSAGE;
    }

    /**
     * Retuns the message
     *
     * @return A string containing a simple message
     */
    public String getMessage() {
        return ">>>>> " + getType() + ":\n" + message + ">>>>>\n\n";
    }

    /**
     * Return a detailed message
     *
     * @return A string containing a detailed message
     */
    public String getDetailMessage() {
        return null;  //TODO: To change body of implemented methods use File | Settings | File Templates.
    }
}
