/* Generated By:JavaCC: Do not edit this line. JGSL_ParserConstants.java */
package jgsl.parser;

public interface JGSL_ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int FORMAL_COMMENT = 11;
  int MULTI_LINE_COMMENT = 12;
  int AND = 14;
  int OR = 15;
  int NOT = 16;
  int IF = 17;
  int THEN = 18;
  int ELSE = 19;
  int ELSEIF = 20;
  int TRUE = 21;
  int FALSE = 22;
  int CLEAR = 23;
  int CANVAS = 24;
  int DRAW = 25;
  int TEXT = 26;
  int RECTANGLE = 27;
  int SQUARE = 28;
  int CIRCLE = 29;
  int ELIPSE = 30;
  int ARC = 31;
  int POLYGON = 32;
  int LINE = 33;
  int WAIT = 34;
  int LOG = 35;
  int DEBUG = 36;
  int ERROR = 37;
  int WARNING = 38;
  int WRITE = 39;
  int READ = 40;
  int JGSL = 41;
  int VERSION = 42;
  int BEGIN = 43;
  int END = 44;
  int REPEAT = 45;
  int LOOP = 46;
  int BLACK = 47;
  int BLUE = 48;
  int DARK_GRAY = 49;
  int GRAY = 50;
  int GREEN = 51;
  int LIGHT_GRAY = 52;
  int MAGENTA = 53;
  int ORANGE = 54;
  int PINK = 55;
  int RED = 56;
  int WHITE = 57;
  int YELLOW = 58;
  int GRADIENT = 59;
  int FILL = 60;
  int BORDER = 61;
  int FOREGROUND = 62;
  int BACKGROUND = 63;
  int COLOR = 64;
  int DECLARE = 65;
  int DOC = 66;
  int INTEGER_LITERAL = 67;
  int DECIMAL_LITERAL = 68;
  int HEX_LITERAL = 69;
  int OCTAL_LITERAL = 70;
  int FLOATING_POINT_LITERAL = 71;
  int STRING_LITERAL = 72;
  int IDENTIFIER = 73;
  int LETTER = 74;
  int DIGIT = 75;
  int LPAREN = 76;
  int RPAREN = 77;
  int SEMICOLON = 78;
  int COLON = 79;
  int COMMA = 80;
  int ASSIGN = 81;
  int GT = 82;
  int LT = 83;
  int BANG = 84;
  int EQ = 85;
  int LE = 86;
  int GE = 87;
  int NE = 88;
  int SC_OR = 89;
  int SC_AND = 90;
  int PLUS = 91;
  int MINUS = 92;
  int STAR = 93;
  int SLASH = 94;
  int MOD = 95;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 8>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 13>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"elseif\"",
    "\"true\"",
    "\"false\"",
    "\"clear\"",
    "\"canvas\"",
    "\"draw\"",
    "\"text\"",
    "\"rectangle\"",
    "\"square\"",
    "\"circle\"",
    "\"elipse\"",
    "\"arc\"",
    "\"polygon\"",
    "\"line\"",
    "\"wait\"",
    "\"log\"",
    "\"debug\"",
    "\"error\"",
    "\"warning\"",
    "\"write\"",
    "\"read\"",
    "\"jgsl\"",
    "\"version\"",
    "\"begin\"",
    "\"end\"",
    "\"repeat\"",
    "\"loop\"",
    "\"black\"",
    "\"blue\"",
    "\"dark_gray\"",
    "\"gray\"",
    "\"green\"",
    "\"light_gray\"",
    "\"magenta\"",
    "\"orange\"",
    "\"pink\"",
    "\"red\"",
    "\"white\"",
    "\"yellow\"",
    "\"gradient\"",
    "\"fill\"",
    "\"border\"",
    "\"foreground\"",
    "\"background\"",
    "\"color\"",
    "\"declare\"",
    "\"doc\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
